---
abstract: 'A class library for flexible, reactive programming.'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300016, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reflex
requires:
  Moose: 2.0203
  MooseX::Role::Parameterized: 0.23
  POE: 1.294
  Scalar::Util: 1.23
  Test::More: 0.96
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Reflex
  repository: git://github.com/rcaputo/reflex.git
version: 0.098
