--- #YAML:1.0
name:               Reflex
version:            0.003
abstract:           Reactive classes for flexible programs.
author:
    - Rocco Caputo <rcaputo@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:         0.92
    POE:           1.268
    Scalar::Util:  1.21
    Test::More:    0.94
resources:
    license:     http://dev.perl.org/licenses/
    repository:  http://github.com/rcaputo/reflex
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
