---
abstract: 'Class library for flexible, reactive programs.'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100922'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reflex
recommends: {}
requires:
  Moose: 0.92
  POE: 1.268
  Scalar::Util: 1.21
  Test::More: 0.94
resources:
  repository: http://github.com/rcaputo/reflex
version: 0.060
